Source Code/LSS/LSS/Models/CourseFileCheckList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseFileCheckList
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Display(Name = "Coordinator Signature")]
        public Nullable<bool> CoordinatorSignature { get; set; }

        [Display(Name = "Head OF Dept Signature")]
        public Nullable<bool> HeadOFDeptSignature { get; set; }

        [Display(Name = "Vice Dean Signature")]
        public Nullable<bool> ViceDeanSignature { get; set; }

        [Display(Name = "Reason Of Disaproval")]
        public string ReasonOfDisaproval { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}

Source Code/LSS/LSS/Models/CourseInformationForm.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseInformationForm
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Display(Name = "Coordinator Signature")]
        public Nullable<bool> CoordinatorSignature { get; set; }

        [Display(Name = "Head OF Dept Signature")]
        public Nullable<bool> HeadOFDeptSignature { get; set; }

        [Display(Name = "Vice Dean Signature")]
        public Nullable<bool> ViceDeanSignature { get; set; }

        [Display(Name = "Reason Of Disaproval")]
        public string ReasonOfDisaproval { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}

Source Code/LSS/LSS/Models/CourseReport.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseReport
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Display(Name = "Coordinator Signature")]
        public Nullable<bool> CoordinatorSignature { get; set; }

        [Display(Name = "Head OF Dept Signature")]
        public Nullable<bool> HeadOFDeptSignature { get; set; }

        [Display(Name = "Vice Dean Signature")]
        public Nullable<bool> ViceDeanSignature { get; set; }

        [Display(Name = "Reason Of Disaproval")]
        public string ReasonOfDisaproval { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}

Source Code/LSS/LSS/Models/CourseSyllabu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseSyllabu
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Display(Name = "Coordinator Signature")]
        public Nullable<bool> CoordinatorSignature { get; set; }

        [Display(Name = "Head OF Dept Signature")]
        public Nullable<bool> HeadOFDeptSignature { get; set; }

        [Display(Name = "Reason Of Disaproval")]
        public string ReasonOfDisaproval { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}

Source Code/LSS/LSS/Controllers/FormsController.cs
using LSS.Models;
using LSS.Models.arc;
using LSS.Models.CoursesModelView;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LSS.Controllers
{
   [Authorize]
    public class FormsController : Controller
    {
        private readonly LSS_databaseEntities _DatabaseEntities = new LSS_databaseEntities();
        // GET: Forms

        public ActionResult CourseAssessmentSurvey(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester==null)
            {
                return new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                return new HttpStatusCodeResult(404);

            }
            return View(cc);
        }

        public ActionResult CourseFileChecklist(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
                return new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                return new HttpStatusCodeResult(404);

            }
            return View(cc);
        }

        public ActionResult CourseInformationForm(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
              return  new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                return new HttpStatusCodeResult(404);

            }
            CouresModelView cmv = new CouresModelView()
            {
                CourseCoordinator = cc
            };
            return View(cmv);
        }

        public ActionResult CourseReport(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
                return new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                return new HttpStatusCodeResult(404);

            }
            CouresReportModelView cmv = new CouresReportModelView(cc);
            return View(cmv);
        }

        public ActionResult CourseSyllabus(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
                new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                new HttpStatusCodeResult(404);

            }
            CouresReportModelView cmv = new CouresReportModelView(cc);
            return View(cmv);
        }

        public ActionResult ExamEvaluation(int? ExamID)
        {
            if (ExamID == null )
            {
                new HttpStatusCodeResult(404);
            }
            CourseExam exam = _DatabaseEntities.CourseExams.Find(ExamID);


            if (exam == null)
            {
                new HttpStatusCodeResult(404);

            }

            ExamEvalCal examEvalCal = new ExamEvalCal()
            {
                exam = exam
            };


           return View(examEvalCal);
        }

        public ActionResult ExamModerationChecklist(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
                new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                new HttpStatusCodeResult(404);

            }

            return View();
        }

        public ActionResult QuestionsAnswersSheet(string? CourseID, DateTime? Year, string? Semester)
        {
            if (CourseID == null || Year == null || Semester == null)
            {
                new HttpStatusCodeResult(404);
            }
            CourseCoordinator cc = _DatabaseEntities.CourseCoordinators.Find(CourseID, Year, Semester);
            if (cc == null)
            {
                new HttpStatusCodeResult(404);

            }
            return View();
        }

    }
}

Source Code/LSS/LSS/Views/Forms/CourseSyllabus.cshtml
@model LSS.Models.CoursesModelView.CouresReportModelView
@using LSS.Models


<header>
    @{
        ViewBag.Title = "CourseSyllabus";
        Layout = "~/Views/Shared/_Layout.cshtml";
        <link rel="stylesheet" href="~/Content/FormsStyle.css" />
       
    }
</header>


<body>
    <div class="row">
        <div class="col-2 mt-lg-5">
            <div class="list-group list-group-flush w-50">
                <h4 class="text-primary text-decoration-none" style="color:black !important"> <b>Content</b> </h4>

                @Html.ActionLink("Recomandations for improving the course", "ActionsForImproving", "CourseCoordinator",
               new { courseId = Model.CourseCoordinator.CourseID }, new { @class = "bg-transparent pb-3" })

                @Html.ActionLink("Students List", "CourseStudentList", "Students",
               new { CourseID = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester },
               new { @class = "bg-transparent pb-3" })

                @Html.ActionLink("Survey", "CourseAssessmentSurvey", "CourseCoordinator",
               new { CourseID = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester },
               new { @class = "bg-transparent pb-3" })

                @Html.ActionLink("Exams & Tasks", "ListCourseExamsAndTasks", "Exam",
               new { CourseID = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester },
               new { @class = "bg-transparent pb-3" })


                @Html.ActionLink("schedule", "CourseSchedule", "CourseCoordinator",
               new { CourseID = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester },
               new { @class = "bg-transparent pb-3" })


                <br />
                <h4 class="text-primary text-decoration-none" style="color:black !important"> <b>Forms</b> </h4>
                @Html.ActionLink("Coures Syllabus", "CourseSyllabus", "Forms", new { courseId = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })
                @Html.ActionLink("Course File Checklist", "CourseFileChecklist", "Forms", new { courseId = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })
                @Html.ActionLink("Course Information Form", "CourseInformationForm", "Forms", new { courseId = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })
                @Html.ActionLink("Coures Report", "CourseReport", "Forms", new { courseId = Model.CourseCoordinator.CourseID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })

            </div>
            </div>
        <div class="col-lg-8">
            <div class="container shadow-lg p-3 mb-3 mt-5 align-content-center bg-white">
                <div class="d-flex justify-content-center align-items-center text-center">
                    <div>
                        <img src="~/Images/LOGO-removebg-preview.png" class="brand_logo" alt="Logo" style="height:150px; width:120px;" />
                        <h3>Faculty of Information Technology </h3>
                    </div>
                </div>

                <hr style="border: 2px solid black" />

                <table id="FormName">
                    <tr class="text-center">
                        <td bgcolor="silver" style="border:1px solid black" class="pt-2">
                            <h4 align="center"> <b>Course Syllabus</b> </h4>
                        </td>
                    </tr>
                </table>

                <br />
                <br />
            
                <table class="table" style="border:double">
                    <tr>
                        <th style=" border:1px solid black" bgcolor="silver" colspan="4"> General Information:</th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Faculty</th>
                        <td style=" border:1px solid black">
                            @Html.DisplayFor(x => x.Department.Faculty.Name)
                        </td>
                        <th style=" border:1px solid black" bgcolor="grey"> Department</th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.Course.Department.Name) </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Academic Year </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.Year.Year) </td>
                        <th style=" border:1px solid black" bgcolor="grey"> Semester </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.Semester) </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="silver" colspan="4"> Course Information:</th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Course Name</th>
                        <td style=" border:1px solid black"> @Html.DisplayFor(x => x.CourseCoordinator.Course.Title)  </td>
                        <th style=" border:1px solid black" bgcolor="grey"> Course No. </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.CourseID) </td>
                    </tr>
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black"> Pre-requisite </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.Course.Course3.Title)  </td>
                        <th bgcolor="silver" style=" border:1px solid black"> Co-requisite </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.Course.Course2.Title) </td>
                    </tr>
                    <tr>
                        <td style=" border:1px solid black" bgcolor="grey"><b>Credit Hours</b><br />(Theory, Practical)</td>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.Course.Hours) </td>
                        <td style=" border:1px solid black" bgcolor="grey"> <b>Designation</b> <br /> (Req. or Elec.)</td>
                        <td style=" border:1px solid black"> @Html.DisplayFor(x => x.CourseCoordinator.Course.Designation)</td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Course Day/Time</th>
                        <td style=" border:1px solid black"> @Html.DisplayFor(x => x.CourseCoordinator.DayTime)</td>
                        <th style=" border:1px solid black" bgcolor="grey"> Class Room </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.ClassRoom) </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Web Address</th>
                        <td style=" border:1px solid black" colspan="3">
                            <a href="@Model.CourseCoordinator.Course.VclassURL">
                                @Html.DisplayFor(x => x.CourseCoordinator.Course.VclassURL)
                            </a>

                        </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" colspan="4" bgcolor="silver"> Instructor/Coordinator Information: </th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Instructor Name</th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.Lecturer.Name) </td>
                        <th style=" border:1px solid black" bgcolor="grey"> E-mail </th>
                        <td style=" border:1px solid black">
                            @Html.DisplayFor(x => x.CourseCoordinator.Lecturer.Email)

                        </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="grey"> Office No. </th>
                        <td style=" border:1px solid black">@Html.DisplayFor(x => x.CourseCoordinator.Lecturer.OfficeNo) </td>
                        <th style=" border:1px solid black" bgcolor="grey"> Office Hours  </th>
                        <td style=" border:1px solid black">1-2 Tuesday </td>
                    </tr>
                </table>
                <br />
                <br />
                <table class="table" style="border:double">
                    <tr>
                        <th style=" border:1px solid black" bgcolor="silver"> Course Description: </th>
                    </tr>
                    <tr>
                        <td style=" border:1px solid black"> @Html.DisplayFor(x => x.CourseCoordinator.Course.Description)  </td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" bgcolor="silver"> References:  </th>
                    </tr>
                    <tr>
                        <td style=" border:1px solid black" bgcolor="silver"> <b>Textbook(s):</b> Author, A. A. (Year published). Book title (Edition). City, State: Publisher.  </td>
                    </tr>
                    <tr>
                        <td style=" border:1px solid black">  </td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
    <hr />
</body>

<footer class="justify-content-center align-items-center d-flex">
    <table>
        <tr>

            <td> <img src="~/Images/R.PNG" /> </td>
            <td><img src="~/Images/Quality.PNG" /> </td>
            <td><img src="~/Images/Risk.PNG" /></td>
            <td>
                <b>
                    EP-F891, Rev. a<br />
                    Ref.: 15/06/2019 - 2020<br />
                    Date: 10/10/2019
                </b>

            </td>

            <td> <img src="~/Images/Certified.PNG" /> </td>
        </tr>
    </table>
</footer>

Source Code/LSS/LSS/Views/Forms/QuestionsAnswersSheet.cshtml
<head>

    @{
        ViewBag.Title = "QuestionsAnswersSheet";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <link href="~/Content/FormsStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>



<body>
    <div class="row">
        <div class="col-2 mt-lg-5">
            @*<div class="list-group list-group-flush w-50">
                    <h4 class="text-primary text-decoration-none" style="color:black !important"> <b>Content</b> </h4>
                    @Html.ActionLink("Recomandations for improving the course", "ActionsForImproving", "CourseCoordinator",
                   new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })

                    @Html.ActionLink("Students List", "CourseStudentList", "CourseCoordinator",
                   new { CourseID = Model.Course.ID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })

                    @Html.ActionLink("PI Assessment", "PI Assessment", "CourseCoordinator",
                   new { CourseID = Model.Course.ID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })

                    @Html.ActionLink("Survey", "CourseAssessmentSurvey", "CourseCoordinator",
                   new { CourseID = Model.Course.ID, Year = Model.CourseCoordinator.Year, Semester = Model.CourseCoordinator.Semester }, new { @class = "bg-transparent pb-3" })
                    <br />
                    <h4 class="text-primary text-decoration-none" style="color:black !important"> <b>Forms</b> </h4>
                    @Html.ActionLink("Coures Syllabus", "CourseSyllabus", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                    @Html.ActionLink("Course Assessment Survey", "CourseAssessmentSurvey", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                    @Html.ActionLink("Course File Checklist", "CourseFileChecklist", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3 text-success" })
                    @Html.ActionLink("Course Information Form", "CourseInformationForm", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                    @Html.ActionLink("Coures Report", "CourseReport", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                    @Html.ActionLink("Exam Evaluation", "ExamEvaluation", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                    @Html.ActionLink("Question Answer Sheet", "QuestionsAnswersSheet", "Forms", new { courseId = Model.Course.ID }, new { @class = "bg-transparent pb-3" })
                </div>*@
        </div>

        <div class="col-lg-8">
            <div class="container shadow-lg p-3 mb-3 mt-5 align-items-center bg-white">
                <div class="d-flex justify-content-center align-items-center text-center">
                    <div>
                        <img src="~/Images/LOGO-removebg-preview.png" class="brand_logo" alt="Logo" style="height:150px; width:120px;" />
                        <h3>Faculty of Information Technology </h3>
                    </div>
                </div>
                <hr style="border: 2px solid black" />



                <table id="FormName" class="mb-4">
                    <tr class="text-center">
                        <td bgcolor="silver" style="border:1px solid black" class="pt-2">
                            <h4 align="center"> <b>Questions/Answers Sheet</b> </h4>
                        </td>
                    </tr>
                </table>

                <pre><b>Form Code:(      )   Date:__________________</b> </pre>

                <table class="table table-responsive-sm">
                    <tr>
                        <th style=" border:1px solid black"> Faculty</th>
                        <th style=" border:1px solid black"> Department</th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black"> Academic Year: </th>
                        <th style=" border:1px solid black"> Semester: </th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black"> Course Name:</th>
                        <th style=" border:1px solid black"> Course No.: </th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" colspan="2"> Test/Exam: </th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black"> Duration:</th>
                        <th style=" border:1px solid black"> No. of  Pages: </th>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black"> Instructor: </th>
                        <th style=" border:1px solid black"> Coordinator:  </th>
                    </tr>
                </table>

                <br />

                <table class="table table-responsive-sm">
                    <tr>
                        <th style=" border:1px solid black"> Student Name: </th>
                        <th style=" border:1px solid black"> Reg. No.: </th>
                    </tr>
                </table>
                <br />



                <table class="table table-responsive-sm">
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black"> Question<br /> No.</th>
                        <th bgcolor="silver" style=" border:1px solid black"> Course <br />Learning <br />Outcome(s)</th>
                        <th bgcolor="silver" style=" border:1px solid black"> Student<br /> Learning <br />Outcome(s)</th>
                        <th bgcolor="silver" style=" border:1px solid black"> Performance<br /> Indicator(s)<br />(if applicable)</th>
                        <th bgcolor="silver" style=" border:1px solid black"> Assigned <br />Mark</th>
                        <th bgcolor="silver" style=" border:1px solid black"> Awarded  Mark</th>
                    </tr>
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black" align="center"><p align="center"> Q1 </p> </th>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black" align="center"> /</td>
                    </tr>
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black" align="center"><p align="center"> Q2 </p> </th>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black" align="center"> /</td>
                    </tr>
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black" align="center"><p align="center"> Q3 </p> </th>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black" align="center"> /</td>
                    </tr>
                    <tr>
                        <th bgcolor="silver" style=" border:1px solid black" align="center"> <p align="center">Q4 </p></th>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black"> </td>
                        <td style=" border:1px solid black" align="center"> /</td>
                    </tr>
                    <tr>
                        <th style=" border:1px solid black" colspan="5"> Total </th>
                        <td style=" border:1px solid black" align="center"> /</td>
                    </tr>
                </table>


                <br />

                <br />
                <pre class="text-left font-weight-bolder"><h5 class="font-weight-bolder"><b>Exam/Test instructions:</b></h5>
•   Students must be in possession of all items they need during the exam/ Test. Borrowing from others is not permitted.
•   Students must report to the assigned room ten minutes before the official start time.
•   Mobile phones are not Permitted in the examination room.
•   Students must display current photo identification.
•   Cheating is strictly forbidden.
•   Students are expected to keep quiet throughout the exam/ Test. Asking questions is not permitted except when absolutely necessary.
•   Only blue or black pens are permitted.</pre>
                <br />
            </div>
        </div>
    </div>
</body>




<br />
<hr />

<footer class="justify-content-center align-items-center d-flex">
    <table>
        <tr>

            <td> <img src="~/Images/R.PNG" /> </td>
            <td><img src="~/Images/Quality.PNG" /> </td>
            <td><img src="~/Images/Risk.PNG" /></td>
            <td>
                <b>
                    EP-F891, Rev. a<br />
                    Ref.: 15/06/2019 - 2020<br />
                    Date: 10/10/2019
                </b>

            </td>

            <td> <img src="~/Images/Certified.PNG" /> </td>
        </tr>
    </table>
</footer>