Source Code/LSS/LSS/Models/Faculty/HeadOfDepartment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LSS.Models
{
    public class HeadOfDepartment : FacultyMember
    {
        public List<Course> DepartmentCourses { get; set; }
        public  Deparment Deparment { get; set; }
    }
}

Source Code/LSS/LSS/Controllers/HeadOfDepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LSS.Models;
using LSS.Models.DepartmentViewModel;

namespace LSS.Controllers
{
    [Authorize]
    public class HeadOfDepartmentController : Controller
    {
        private readonly  LSS_databaseEntities _databaseEntities = new LSS_databaseEntities();
        // GET: HeadOfDepartment
        //todo remove = 2 
        public ActionResult Index(int? dptID )
        {
            if (dptID == null)
            {
                dptID = int.Parse(Session["Dpt"].ToString());
            }
            Department d = _databaseEntities.Departments.Find(dptID);
            return View(d);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSLO(AddSLOMV md,String[] PEOID)
        {
            
                if (ModelState.IsValid)
                {
                    List<PEO> PEOs = md.PEOs.ToList();
                    _databaseEntities.Entry(md.SLO).State = EntityState.Modified;
                    _databaseEntities.SaveChanges();
                    List<SLO_PEO> sLO_PEOs = _databaseEntities.SLO_PEO.Where(x => x.SLOID.Equals(md.SLO.SLOID) && x.DeptID.Equals(md.SLO.DeptID)).ToList();
                    foreach (PEO peo in PEOs)
                    {
                        SLO_PEO SLO_PEO = new SLO_PEO();
                        if (PEOID != null && PEOID.Contains(peo.ID))
                        {
                            if (!sLO_PEOs.Select(x => x.PEOID).Contains(peo.ID))
                            {
                                SLO_PEO.SLOID = md.SLO.SLOID;
                                SLO_PEO.DeptID = md.SLO.DeptID;
                                SLO_PEO.PEOID = peo.ID;
                                _databaseEntities.SLO_PEO.Add(SLO_PEO);
                                _databaseEntities.SaveChanges();
                            }
                        }
                        else
                        {
                            if (sLO_PEOs.Select(x => x.PEOID).Contains(peo.ID))
                            {

                                SLO_PEO = _databaseEntities.SLO_PEO.Single(i => i.DeptID.Equals(md.SLO.DeptID)
                                        && i.SLOID.Equals(md.SLO.SLOID)
                                        && i.PEOID.Equals(peo.ID));
                                _databaseEntities.SLO_PEO.Remove(SLO_PEO);
                                _databaseEntities.SaveChanges();
                            }
                        }
                    }
                    return RedirectToAction("Index", md.SLO.DeptID);
                }
                return View(md);


        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult AddPI(PI pi)
        {
            

                _databaseEntities.PIs.Add(pi);
                _databaseEntities.SaveChanges();

                return RedirectToAction("index", pi.DeptID);
     
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult AddSLO(AddSLOMV md, String[] PEOID)
        {
           
                if (ModelState.IsValid)
            {
                _databaseEntities.SLOes.Add(md.SLO);
                _databaseEntities.SaveChanges();
                SLO_PEO SLO_PEO = new SLO_PEO();

                foreach (String str in PEOID)
                {
                    SLO_PEO.SLOID = md.SLO.SLOID;
                    SLO_PEO.DeptID = md.SLO.DeptID;
                    SLO_PEO.PEOID = str;
                    _databaseEntities.SLO_PEO.Add(SLO_PEO);
                }
                _databaseEntities.SaveChanges();
                return RedirectToAction("index", new { d = md.SLO.DeptID });
            }
            return View(md);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult AddPEO(PEO peo)
        {
        
                if (ModelState.IsValid)
            {
                _databaseEntities.PEOs.Add(peo);
                _databaseEntities.SaveChanges();
                return RedirectToAction("index", new { d = peo.DeptID });
            }
            return View();
            }
       
    }
}

Source Code/LSS/LSS/Views/HeadOfDepartment/AddPEO.cshtml
@model LSS.Models.PEO

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


@using (Html.BeginForm("AddPEO", "HeadOfDepartment", FormMethod.Post))
{



    @Html.AntiForgeryToken()

    <div class="container">
        <h4 class="text-center mt-2">PEO</h4>
        <hr style="border-color:red;" class="w-75" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="container shadow-sm p-2">

            @Html.HiddenFor(model => model.DeptID)
            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="sloId">ID</span>
                </div>
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control", id = "ID", style = "max-width:100%" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="desc">Descreption</span>
                </div>
                @Html.TextAreaFor(model => model.Desc, new { @class = "form-control", id = "Desc" })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="justify-content-center align-items-center text-center mt-3">
            <input type="submit" value="Add" asp-action="AddPEO" id="PartialSubmit" class="btn btn-primary" disabled/>
            <div class="text-right mb-2">
                @Html.ActionLink("Cancel", "Index" ,"HeadOfDepartment")
            </div>
        </div>
    </div>
    <script>
      
        $("#ID").change(function () {
            console.log($("#ID").val());
            if ($("#ID").val() && $("#Desc").val()) {
                $("#PartialSubmit").prop('disabled', false);
            } else
                $("#PartialSubmit").prop('disabled', true);
        });
        $("#Desc").change(function () {
            console.log($("#Desc").val());
            if ($("#ID").val() && $("#Desc").val()) {
                $("#PartialSubmit").prop('disabled', false);
            } else
                $("#PartialSubmit").prop('disabled', true);
        });

    </script>
}

Source Code/LSS/LSS/Views/HeadOfDepartment/AddPI.cshtml
@model LSS.Models.PI


@using (Html.BeginForm("AddPI", "HeadOfDepartment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="container">
    <h4 class="text-center mt-2">PI</h4>
    <hr style="border-color:red;" class="w-75" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="container shadow-sm p-2">
        <div class="input-group mb-3 w-75">
            <div class="input-group-prepend">
                <span class="input-group-text text-primary" id="deptId">Dept ID</span>
            </div>
            @Html.EditorFor(model => model.DeptID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.DeptID, "", new { @class = "text-danger" })
        </div>

        <div class="input-group mb-3 w-75">
            <div class="input-group-prepend">
                <span class="input-group-text text-primary" id="sloId">SLO ID</span>
            </div>
            @Html.EditorFor(model => model.SLOID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.SLOID, "", new { @class = "text-danger" })
        </div>

        <div class="input-group mb-3 w-75">
            <div class="input-group-prepend">
                <span class="input-group-text text-primary" id="desc">ID</span>
            </div>
            @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
        </div>

        <div class="input-group mb-3 w-75">
            <div class="input-group-prepend">
                <span class="input-group-text text-primary" id="desc">Descreption</span>
            </div>
            @Html.TextAreaFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
        </div>
    </div>





    @*<div class="form-group">
            @Html.LabelFor(model => model.DeptID, "DeptID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SLOID, "SLOID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

            </div>
        </div>*@







    <div class="justify-content-center align-items-center text-center mt-3">
        <input type="submit" value="Create" class="btn btn-primary" />
        <div class="text-right mb-2">
            @Html.ActionLink("Cancel", "Index", "HeadOfDepartment", Model.DeptID)
        </div>
    </div>
</div>
}

Source Code/LSS/LSS/Views/HeadOfDepartment/AddSLO.cshtml
@model LSS.Models.DepartmentViewModel.AddSLOMV
@using LSS.Models
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
@using (Html.BeginForm("AddSLO", "HeadOfDepartment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <h4 class="text-center mt-2">SLO</h4>
        <hr style="border-color:red;" class="w-75" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container shadow-sm">
            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="deptId">Dept ID</span>
                </div>
                @Html.EditorFor(model => model.SLO.DeptID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
                @Html.ValidationMessageFor(model => model.SLO.DeptID, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="sloId">SLO ID</span>
                </div>
                @Html.EditorFor(model => model.SLO.SLOID, new { htmlAttributes = new { @class = "form-control", id = "IDSLO" } })
                @Html.ValidationMessageFor(model => model.SLO.SLOID, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="desc">Descreption</span>
                </div>
                @Html.TextAreaFor(model => model.SLO.Desc,  new { @class = "form-control", id = "DescSLO" })
                @Html.ValidationMessageFor(model => model.SLO.Desc, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.Label(" Select all PEO to MAP to this SLO")
                <ul style="list-style-type:none; flex:auto">
                    @foreach (PEO peo in Model.PEOs)
                    {
                        <li>
                            <input type="checkbox" id="PEOID" name="PEOID" value="@peo.ID" checked="@Model.SLO.SLO_PEO.Select(x => x.PEOID).Contains(peo.ID)" /> <b style="padding-bottom:2%; margin-bottom:2%">@peo.ID</b>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="justify-content-center align-items-center text-center">
            <input type="submit" value="Add SLO" class="btn btn-primary" id="PartialSubmitSLO" disabled />
            <div class="text-right mb-2">
                @Html.ActionLink("Cancel", "Index", "HeadOfDepartment", Model.SLO.DeptID)
            </div>
        </div>
    </div>
    <script>
       
        $("#IDSLO").change(function () {
            
            if ($("#IDSLO").val() && $("#DescSLO").val()) {
                $("#PartialSubmitSLO").prop('disabled', false);
            } else {
                $("#PartialSubmitSLO").prop('disabled', true);
                console.log($("#IDSLO").val());
            }
          
        });
        $("#DescSLO").change(function () {
            console.log($("#Desc").val());
            if ($("#IDSLO").val() && $("#DescSLO").val()) {
                $("#PartialSubmitSLO").prop('disabled', false);
            } else {
                $("#PartialSubmitSLO").prop('disabled', true);
                console.log($("#DescSLO").val());
            }
        });

    </script>
}

Source Code/LSS/LSS/Views/HeadOfDepartment/EditSLO.cshtml
@model LSS.Models.DepartmentViewModel.AddSLOMV
@using LSS.Models


@using (Html.BeginForm("EditSLO", "HeadOfDepartment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <h4 class="text-center mt-2">SLO</h4>
        <hr style="border-color:red;" class="w-75" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="container shadow-sm">
            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="deptId">Dept ID</span>
                </div>
                @Html.EditorFor(model => model.SLO.DeptID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.SLO.DeptID, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="sloId">SLO ID</span>
                </div>
                @Html.EditorFor(model => model.SLO.SLOID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.SLO.SLOID, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mb-3 w-75">
                <div class="input-group-prepend">
                    <span class="input-group-text text-primary" id="desc">Descreption</span>
                </div>
                @Html.TextAreaFor(model => model.SLO.Desc, new { @class = "form-control", id = "DescSLO" })
                @Html.ValidationMessageFor(model => model.SLO.Desc, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.Label(" Select all PEO to MAP to this SLO")
                <ul style="list-style-type:none; flex:auto">
                    @foreach (PEO peo in Model.PEOs)
                    {
                        <li>
                            <input type="checkbox" id="PEOID" name="PEOID" value="@peo.ID" checked="@Model.SLO.SLO_PEO.Select(x => x.PEOID).Contains(peo.ID)" /> <b style="padding-bottom:2%; margin-bottom:2%">@peo.ID</b>
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="justify-content-center align-items-center text-center">
            <input type="submit" value="Edit SLO" class="btn btn-primary " />
            <div class="text-right mb-2">
                @Html.ActionLink("Cancel", "Index", "HeadOfDepartment", Model.SLO.DeptID)
            </div>
        </div>
    </div>



    <script>
        $("#DescSLO").change(function () {
            console.log($("#Desc").val());
            if ($("#IDSLO").val() && $("#DescSLO").val()) {
                $("#PartialSubmitSLO").prop('disabled', false);
            } else {
                $("#PartialSubmitSLO").prop('disabled', true);
                console.log($("#DescSLO").val());
            }
        });

    </script>
}

Source Code/LSS/LSS/Views/HeadOfDepartment/Index.cshtml
@using LSS.Models
@model LSS.Models.Department
@using LSS.Models.DepartmentViewModel

<head>
    @{
        ViewBag.Title = Model.Name;
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
</head>

<script>
    $(function () {
        var PlaceHolderElement = $('#PlaceHolderHere');
        $('button[data-toggle="ajax-model"]').click(function (event) {
            var url = $this(this).data('url');
            var decodedURL = decodeURIComponent(url);
            $.get(url).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('modal').modal('show');
            })
        })

        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            var form = $(this).parent('.modal').find('form');
            var actionUrl = form.attr('action');
            var sendData = form.serialize();
            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find(',modal').modal('hide');
            })
        }
})



    $(function () {
        var PlaceHolderElement = $('#PlaceHolderHere');
        $('button[data-toggle="ajax-model"]').click(function (event) {
            var url = $this(this).data('url');
            var decodedURL = decodeURIComponent(url);
            $.get(url).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('modal').modal('show');
            })
        })

        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            var form = $(this).parent('.modal').find('form');
            var actionUrl = form.attr('action');
            var sendData = form.serialize();
            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find(',modal').modal('hide');
            })
        }
})
</script>

<body class="container">
    <div class="shadow-lg mb-3 mt-5 align-content-center bg-white">
        <div class="d-flex justify-content-center align-items-center text-center">
            <div class="mt-2">
                <img src="~/Images/LOGO-removebg-preview.png" class="brand_logo" alt="Logo" style="height:150px; width:120px;" />
                <h2>@Model.Name</h2>
            </div>
        </div>

        <div class="container shadow-sm">
            <h2 class="pt-2">Department Informatin</h2>
            <hr style="border-color:red;" class="align-items-start" />
            <table class="dl-horizontal" style="width:100%">
                <tr>
                    <td>
                        <h4>@Html.DisplayNameFor(model => model.Name)</h4>
                    </td>
                    <td>
                        <h4>@Html.DisplayFor(model => model.Name)</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4>@Html.DisplayName("Faculty")</h4>
                    </td>
                    <td>
                        <h4>@Html.DisplayFor(model => model.Faculty.Name)</h4>
                    </td>
                </tr>

                <tr>
                    <td>
                        <h4> @Html.DisplayName("Head OF Department")</h4>
                    </td>

                    <td>
                        <h4>@Html.DisplayFor(model => model.Lecturer.Name)</h4>
                    </td>
                </tr>
            </table>

            <div>
                <h2>
                    Program Educational Opjectives (PEO)
                </h2>
                @if (Model.PEOs != null)
                {
                    <ul>
                        @foreach (PEO peo in Model.PEOs)
                        {
                            <li>
                                <h5>
                                    <b> @peo.ID : </b>
                                </h5>
                                <p>
                                    @peo.Desc
                                </p>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <h3> There is'nt any PEO yet. </h3>
                }
            </div>

            @if (User.Identity.Name.Equals(Model.HeadOFDepartment))
            {
                <div id="addPEO" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            @{
                                Html.RenderPartial("AddPEO", new PEO(Model.ID));
                            }
                        </div>
                    </div>
                </div>
                <button class="btn btn-outline-primary mb-3" id='open' data-toggle="modal" data-target="#addPEO">Add PEO</button>
            }
        </div>
        <hr style="border-color:red;" class="align-items-start mt-3" />



        <div class="container shadow-sm">
            <h2 class="pt-2">Student Learning Outcome (SLO)</h2>
            <div>
                <table class="table table-hover">
                    @foreach (SLO slo in Model.SLOes)
                    {
                        <tr>
                            <td>
                                <div>
                                    <h5 class="text-left pr-1"><b>@slo.SLOID</b></h5>
                                    <p> @slo.Desc </p>
                                </div>
                            </td>

                            <td class="text-white">
                                @if (User.Identity.Name.Equals(Model.HeadOFDepartment))
                                {
                                    <a class="btn btn-primary" id="open" data-toggle="modal" data-target="#@slo.SLOID">Edit</a>
                                    <a class="btn btn-primary" id="open" data-toggle="modal" data-target="#PI_@slo.SLOID">Add PI </a>
                                }
                                <div id="PI_@slo.SLOID" class="modal fade" tabindex="-1" role="dialog">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            @{
                                                Html.RenderPartial("AddPI", new PI()
                                                {
                                                    SLOID = slo.SLOID,
                                                    DeptID = Model.ID
                                                });
                                            }
                                        </div>
                                    </div>
                                </div>

                                @if (User.Identity.Name.Equals(Model.HeadOFDepartment))
                                {
                                    <div id="@slo.SLOID" class="modal fade" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                @{
                                                    Html.RenderPartial("EditSLO", new AddSLOMV(slo));
                                                }
                                            </div>
                                        </div>
                                    </div>
                                }

                            </td>
                        </tr>


                        <tr>
                            <td colspan=" 2">
                                @foreach (PI pi in slo.PIs)
                                {

                                    <h6><b>@pi.ID : </b></h6>
                                    <p> @pi.Desc</p>
                                }
                            </td>
                        </tr>
                    }
                </table>
                @if (User.Identity.Name.Equals(Model.HeadOFDepartment))
                {
                    <div id="addSLO" class="modal fade" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                @{
                                    Html.RenderPartial("AddSLO", new AddSLOMV(Model.ID));
                                }
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-outline-primary mb-3" id='open' data-toggle="modal" data-target="#addSLO">Add SLO</button>
                }
            </div>
        </div>

        <hr style="border-color:red;" class="align-items-start mt-3" />

        <div class="container shadow-sm mt-3">
            <h2 class="text-center">PEO-SLO</h2>
            <div>
                @{ Html.RenderPartial("_PEO_SLO_Mapping", new MappedPEO_SLO(Model)); }
            </div>
        </div>
    </div>
</body>

Source Code/LSS/LSS/Views/HeadOfDepartment/_PEO_SLO_Mapping.cshtml
@model LSS.Models.DepartmentViewModel.MappedPEO_SLO
@using LSS.Models

<html>
<body>
    <div class="card-group">
        <div class="col-3 mt-3 text-primary font-weight-bold">
            <ul class="list-unstyled">
                <li>
                    @if (Model != null)
                    {
                        <table class="table-responsive-lg table-borderless">
                            <tr>
                                <td >

                                </td>
                                @for (int i = 0; i < Model.PEOs.Count(); i++)
                                {
                                    <td> @Model.PEOs[i].ID</td>
                                }
                            </tr>
                            @for (int i = 0; i < Model.SLOes.Count(); i++)
                            {
                                <tr>
                                    <td>
                                        @Model.SLOes[i].SLOID
                                    </td>
                                    @for (int j = 0; j < Model.PEOs.Count(); j++)
                                    {
                                        if (Model.SLO_PEO.Where(x => x.SLOID.Equals(Model.SLOes[i].SLOID) && x.PEOID.Equals(Model.PEOs[j].ID)).FirstOrDefault() != null)
                                        {
                                            <td class="justify-content-center align-items-center text-center">
                                                @Html.CheckBox("name", true, new { disabled = true })
                                            </td>
                                        }
                                        else
                                        {
                                            <td class="justify-content-center align-items-center text-center">
                                                @Html.CheckBox("name", false, new { disabled = true })
                                            </td>
                                        }
                                    }
                                </tr>
                            }
                        </table>
                    }
                </li>
            </ul>
        </div>

        <div class="col-6 mt-3" id="PeoSloCard">
            <ul class="list-unstyled text-center justify-content-center align-items-center d-flex w-100">
                @if (Model.UnmappedSLO.Count() > 0)
                {
                    <li class="pr-4">
                        <div class="card border-primary">
                            <div class="card-header">
                                <h4>unmapped SLO to PEO: </h4>
                            </div>
                            <div class="card-body">
                                <blockquote class="blockquote mb-0">
                                    <p class="text-warning"> @Model.UnmappedSLO.Count() </p>
                                </blockquote>
                            </div>
                        </div>
                    </li>
                }


                @if (Model.UnmappedPEO.Count() > 0)
                {
                    <li>
                        <div class="card border-primary">
                            <div class="card-header">
                                <h4>unmapped PEO to SLO: </h4>
                            </div>
                            <div class="card-body">
                                <blockquote class="blockquote mb-0">
                                    <p class="text-warning"> @Model.UnmappedPEO.Count() </p>
                                </blockquote>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</body>
</html>